apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: szwt4gzsr-python
  janus-idp.io/tekton: szwt4gzsr-python
  backstage.io/kubernetes-id: szwt4gzsr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: szwt4gzsr-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
